_target_: algo.prm_prev.PRM

rollout_len: 4
samples_per_epoch: 1024
new_state_portion: 0.1
node_merge_threshold: 0.2
max_num_nodes: 500000
max_children: 100
visualize_reset_states: False
visualize_prm: False
local_planner: policy #random