_target_: algo.prm.PRM

rollout_len: 4
samples_per_epoch: 2048  # 1024
new_state_portion: 0.5
node_merge_threshold: 0.05  # 0.2
max_num_nodes: 50000  # 500000
max_children: 50 # 20
visualize_reset_states: False
visualize_prm: False
compute_max_goal_dist: False
local_planner: policy

#rollout_len: 8
#samples_per_epoch: 1024
#new_state_portion: 0.01  # 0.3
#node_merge_threshold: 0.5  # 0.2
#max_num_nodes: 500000
#max_children: 50
#visualize_reset_states: False
#visualize_prm: False
#compute_max_goal_dist: True
#local_planner: random

#rollout_len: 16
#samples_per_epoch: 1024
#new_state_portion: 0.1  # 0.3
#node_merge_threshold: 1.0  # 0.2
#max_num_nodes: 200000
#max_children: 50
#visualize_reset_states: False
#visualize_prm: False
#compute_max_goal_dist: False
#local_planner: policy